In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/Employee_attrition.csv",
                 na_values=["NA"," "])

In [ ]:
df.shape

(1470, 35)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [ ]:
df['Attrition'].unique()

array(['Yes', 'No'], dtype=object)

In [ ]:
df['BusinessTravel'].unique()

array(['Travel_Rarely', 'Travel_Frequently', 'Non-Travel'], dtype=object)

In [ ]:
for col in df.columns:
  print(col, df[col].unique())

Age [41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]
Attrition ['Yes' 'No']
BusinessTravel ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
DailyRate [1102  279 1373 1392  591 1005 1324 1358  216 1299  809  153  670 1346
  103 1389  334 1123 1219  371  673 1218  419  391  699 1282 1125  691
  477  705  924 1459  125  895  813 1273  869  890  852 1141  464 1240
 1357  994  721 1360 1065  408 1211 1229  626 1434 1488 1097 1443  515
  853 1142  655 1115  427  653  989 1435 1223  836 1195 1339  664  318
 1225 1328 1082  548  132  746  776  193  397  945 1214  111  573 1153
 1400  541  432  288  669  530  632 1334  638 1093 1217 1353  120  682
  489  807  827  871  665 1040 1420  240 1280  534 1456  658  142 1127
 1031 1189 1354 1467  922  394 1312  750  441  684  249  841  147  528
  594  470  957  542  802 1355 1150 1329  959 1033 1316  364  438  689
  201 1427  857  933 1181 1395  662 1436  194  967 1496 1169 1145  630
  303 1256  440 1450 1452  465  702 1157  602 1480 1268  713  134  526
 1380  140  629 1356  328 1084  931  692 1069  313  894  556 1344  290
  138  926 1261  472 1002  878  905 1180  121 1136  635 1151  644 1045
  829 1242 1469  896  992 1052 1147 1396  663  119  979  319 1413  944
 1323  532  818  854 1034  771 1401 1431  976 1411 1300  252 1327  832
 1017 1199  504  505  916 1247  685  269 1416  833  307 1311  128  488
  529 1210 1463  675 1385 1403  452  666 1158  228  996  728 1315  322
 1479  797 1070  442  496 1372  920  688 1449 1117  636  506  444  950
  889  555  230 1232  566 1302  812 1476  218 1132 1105  906  849  390
  106 1249  192  553  117  185 1091  723 1220  588 1377 1018 1275  798
  672 1162  508 1482  559  210  928 1001  549 1124  738  570 1130 1192
  343  144 1296 1309  483  810  544 1062 1319  641 1332  756  845  593
 1171  350  921 1144  143 1046  575  156 1283  755  304 1178  329 1362
 1371  202  253  164 1107  759 1305  982  821 1381  480 1473  891 1063
  645 1490  317  422 1485 1368 1448  296 1398 1349  986 1099 1116 1499
  983 1009 1303 1274 1277  587  413 1276  988 1474  163  267  619  302
  443  828  561  426  232 1306 1094  509  775  195  258  471  799  956
  535 1495  446 1245  703  823 1246  622 1287  448  254 1365  538  525
  558  782  362 1236 1112  204 1343  604 1216  646  160  238 1397  306
  991  482 1176  913 1076  727  885  243  806  817 1410 1207 1442  693
  929  562  608  580  970 1179  294  314  316  654  168  381  217  501
  650  141  804  975 1090  346  430  268  167  621  527  883  954  310
  719  725  715  657 1146  182  376  571  384  791 1111 1243 1092 1325
  805  213  118  676 1252  286 1258  932 1041  859  720  946 1184  436
  589  760  887 1318  625  180  586 1012  661  930  342 1230 1271 1278
  607  130  300  583 1418 1269  379  395 1265 1222  341  868 1231  102
  881 1383 1075  374 1086  781  177  500 1425 1454  617 1085  995 1122
  618  546  462 1198 1272  154 1137 1188  188 1333  867  263  938  129
  616  498 1404 1053  289 1376  231  152  882  903 1379  335  722  461
  974 1126  840 1134  248  955  939 1391 1206  287 1441  109 1066  277
  466 1055  265  135  247 1035  266  145 1038 1234 1109 1089  788  124
  660 1186 1464  796  415  769 1003 1366  330 1492 1204  309 1330  469
  697 1262 1050  770  406  203 1308  984  439  793 1451 1182  174  490
  718  433  773  603  874  367  199  481  647 1384  902  819  862 1457
  977  942 1402 1421 1361  917  200  150  179  696  116  363  107 1465
  458 1212 1103  966 1010  326 1098  969 1167  694 1320  536  373  599
  251  131  237 1429  648  735  531  429  968  879  640  412  848  360
 1138  325 1322  299 1030  634  524  256 1060  935  495  282  206  943
  523  507  601  855 1291 1405 1369  999 1202  285  404  736 1498 1200
 1439  499  205  683 1462  949  652  332 1475  337  971 1174  667  560
  172  383 1255  359  401  377  592 1445 1221  866  981  447 1326  748
  990  405  115  790  830 1193 1423  467  271  410 1083  516  224  136
 1029  333 1440  674 1342  898  824  492  598  740  888 1288  104 1108
  479 1351  474  437  884 1370  264 1059  563  457 1313  241 1015  336
 1387  170  208  671  711  737 1470  365  763  567  486  772  301  311
  584  880  392  148  708 1259  786  370  678  146  581  918 1238  585
  741  552  369  717  543  964  792  611  176  897  600 1054  428  181
  211 1079  590  305  953  478 1375  244  511 1294  196  734 1239 1253
 1128 1336  234  766  261 1194  431  572 1422 1297  574  355  207  706
  280  726  414  352 1224  459 1254 1131  835 1172 1266  783  219 1213
 1096 1251 1394  605 1064 1337  937  157  754 1168  155 1444  189  911
 1321 1154  557  642  801  161 1382 1037  105  582  704  345 1120 1378
  468  613 1023  628]
Department ['Sales' 'Research & Development' 'Human Resources']
DistanceFromHome [ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]
Education [2 1 4 3 5]
EducationField ['Life Sciences' 'Other' 'Medical' 'Marketing' 'Technical Degree'
 'Human Resources']
EmployeeCount [1]
EmployeeNumber [   1    2    4 ... 2064 2065 2068]
EnvironmentSatisfaction [2 3 4 1]
Gender ['Female' 'Male']
HourlyRate [ 94  61  92  56  40  79  81  67  44  84  49  31  93  50  51  80  96  78
  45  82  53  83  58  72  48  42  41  86  97  75  33  37  73  98  36  47
  71  30  43  99  59  95  57  76  87  66  55  32  52  70  62  64  63  60
 100  46  39  77  35  91  54  34  90  65  88  85  89  68  69  74  38]
JobInvolvement [3 2 4 1]
JobLevel [2 1 3 4 5]
JobRole ['Sales Executive' 'Research Scientist' 'Laboratory Technician'
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
JobSatisfaction [4 2 3 1]
MaritalStatus ['Single' 'Married' 'Divorced']
MonthlyIncome [5993 5130 2090 ... 9991 5390 4404]
MonthlyRate [19479 24907  2396 ...  5174 13243 10228]
NumCompaniesWorked [8 1 6 9 0 4 5 2 7 3]
Over18 ['Y']
OverTime ['Yes' 'No']
PercentSalaryHike [11 23 15 12 13 20 22 21 17 14 16 18 19 24 25]
PerformanceRating [3 4]
RelationshipSatisfaction [1 4 2 3]
StandardHours [80]
StockOptionLevel [0 1 3 2]
TotalWorkingYears [ 8 10  7  6 12  1 17  5  3 31 13  0 26 24 22  9 19  2 23 14 15  4 29 28
 21 25 20 11 16 37 38 30 40 18 36 34 32 33 35 27]
TrainingTimesLastYear [0 3 2 5 1 4 6]
WorkLifeBalance [1 3 2 4]
YearsAtCompany [ 6 10  0  8  2  7  1  9  5  4 25  3 12 14 22 15 27 21 17 11 13 37 16 20
 40 24 33 19 36 18 29 31 32 34 26 30 23]
YearsInCurrentRole [ 4  7  0  2  5  9  8  3  6 13  1 15 14 16 11 10 12 18 17]
YearsSinceLastPromotion [ 0  1  3  2  7  4  8  6  5 15  9 13 12 10 11 14]
YearsWithCurrManager [ 5  7  0  2  6  8  3 11 17  1  4 12  9 10 15 13 16 14]

In [ ]:
# Fnd all categorical columns
#thumb rule ---> no of unique value < 15
cat_columns = df.columns[df.nunique() <= 15]
cat_columns

Index(['Attrition', 'BusinessTravel', 'Department', 'Education',
       'EducationField', 'EmployeeCount', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TrainingTimesLastYear',
       'WorkLifeBalance'],
      dtype='object')

In [ ]:
cont_columns = df.columns[df.nunique() > 15]
cont_columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'EmployeeNumber', 'HourlyRate',
       'MonthlyIncome', 'MonthlyRate', 'TotalWorkingYears', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
df.isna().sum()#sum func axis=0

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [ ]:
df.shape

(1470, 35)

# Find the id columns and columns where there is only a single unique value

In [ ]:
drop_columns = df.columns[df.nunique() ==1]
drop_columns

Index(['EmployeeCount', 'Over18', 'StandardHours'], dtype='object')

In [ ]:
df.drop(columns=['EmployeeCount','Over18',
                 'StandardHours'], inplace=True)

In [ ]:
df.shape

(1470, 32)

In [ ]:
df.drop(columns=['EmployeeNumber'],inplace=True)
df.shape

(1470, 31)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.shape

(1470, 31)

In [ ]:
# Fnd the object columns

obj_cols = df.select_dtypes(include = "object").columns
obj_cols

Index(['Attrition', 'BusinessTravel', 'Department', 'EducationField', 'Gender',
       'JobRole', 'MaritalStatus', 'OverTime'],
      dtype='object')

## Convert string columns to numbers

- nominal --> One hot encoding (dummy variables)


- ordinal --> label encoding

In [ ]:
#label encoding
label_map={'BusinessTravel':{'Travel_Rarely':1,
            'Travel_Frequently':2,'Non-Travel':0}}
df.replace(label_map,inplace=True)
df['BusinessTravel'].unique()

/tmp/ipykernel_2494/2988944158.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(label_map,inplace=True)

array([1, 2, 0])

In [ ]:
df.dtypes

Age                          int64
Attrition                   object
BusinessTravel               int64
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [ ]:
#OHE
df_ohe = pd.get_dummies(df)
df_ohe.shape,df.shape

((1470, 51), (1470, 31))

In [ ]:
df_ohe.columns

Index(['Age', 'BusinessTravel', 'DailyRate', 'DistanceFromHome', 'Education',
       'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel',
       'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition_No',
       'Attrition_Yes', 'Department_Human Resources',
       'Department_Research & Development', 'Department_Sales',
       'EducationField_Human Resources', 'EducationField_Life Sciences',
       'EducationField_Marketing', 'EducationField_Medical',
       'EducationField_Other', 'EducationField_Technical Degree',
       'Gender_Female', 'Gender_Male', 'JobRole_Healthcare Representative',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'MaritalStatus_Divorced', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'OverTime_No', 'OverTime_Yes'],
      dtype='object')

In [ ]:
df_ohe.dtypes

Age                                  int64
BusinessTravel                       int64
DailyRate                            int64
DistanceFromHome                     int64
Education                            int64
EmployeeNumber                       int64
EnvironmentSatisfaction              int64
HourlyRate                           int64
JobInvolvement                       int64
JobLevel                             int64
JobSatisfaction                      int64
MonthlyIncome                        int64
MonthlyRate                          int64
NumCompaniesWorked                   int64
PercentSalaryHike                    int64
PerformanceRating                    int64
RelationshipSatisfaction             int64
StockOptionLevel                     int64
TotalWorkingYears                    int64
TrainingTimesLastYear                int64
WorkLifeBalance                      int64
YearsAtCompany                       int64
YearsInCurrentRole                   int64
YearsSinceLastPromotion              int64
YearsWithCurrManager                 int64
Attrition_No                          bool
Attrition_Yes                         bool
Department_Human Resources            bool
Department_Research & Development     bool
Department_Sales                      bool
EducationField_Human Resources        bool
EducationField_Life Sciences          bool
EducationField_Marketing              bool
EducationField_Medical                bool
EducationField_Other                  bool
EducationField_Technical Degree       bool
Gender_Female                         bool
Gender_Male                           bool
JobRole_Healthcare Representative     bool
JobRole_Human Resources               bool
JobRole_Laboratory Technician         bool
JobRole_Manager                       bool
JobRole_Manufacturing Director        bool
JobRole_Research Director             bool
JobRole_Research Scientist            bool
JobRole_Sales Executive               bool
JobRole_Sales Representative          bool
MaritalStatus_Divorced                bool
MaritalStatus_Married                 bool
MaritalStatus_Single                  bool
OverTime_No                           bool
OverTime_Yes                          bool
dtype: object

# Fill missing values

In [ ]:
df_ohe.fillna(df_ohe.median(),inplace=True)

In [ ]:
df_ohe.isna().sum()

Age                                  0
BusinessTravel                       0
DailyRate                            0
DistanceFromHome                     0
Education                            0
EnvironmentSatisfaction              0
HourlyRate                           0
JobInvolvement                       0
JobLevel                             0
JobSatisfaction                      0
MonthlyIncome                        0
MonthlyRate                          0
NumCompaniesWorked                   0
PercentSalaryHike                    0
PerformanceRating                    0
RelationshipSatisfaction             0
StockOptionLevel                     0
TotalWorkingYears                    0
TrainingTimesLastYear                0
WorkLifeBalance                      0
YearsAtCompany                       0
YearsInCurrentRole                   0
YearsSinceLastPromotion              0
YearsWithCurrManager                 0
Attrition_No                         0
Attrition_Yes                        0
Department_Human Resources           0
Department_Research & Development    0
Department_Sales                     0
EducationField_Human Resources       0
EducationField_Life Sciences         0
EducationField_Marketing             0
EducationField_Medical               0
EducationField_Other                 0
EducationField_Technical Degree      0
Gender_Female                        0
Gender_Male                          0
JobRole_Healthcare Representative    0
JobRole_Human Resources              0
JobRole_Laboratory Technician        0
JobRole_Manager                      0
JobRole_Manufacturing Director       0
JobRole_Research Director            0
JobRole_Research Scientist           0
JobRole_Sales Executive              0
JobRole_Sales Representative         0
MaritalStatus_Divorced               0
MaritalStatus_Married                0
MaritalStatus_Single                 0
OverTime_No                          0
OverTime_Yes                         0
dtype: int64

In [ ]:
cont_columns = df_ohe.columns[df_ohe.nunique() > 15]
cont_columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'HourlyRate', 'MonthlyIncome',
       'MonthlyRate', 'TotalWorkingYears', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [ ]:
df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()

/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.44619856  1.32191535  0.00834016 ... -1.08630583  1.32191535
 -0.32005364]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.74227393 -1.29733311  1.41388208 ... -1.6046372   0.54649148
 -0.43242077]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-1.01056544 -0.14709966 -0.88721318 ... -0.64050868 -0.88721318
 -0.14709966]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 1.38266773 -0.24059489  1.28428818 ...  1.0383393  -0.14221534
  0.79239041]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.10831265 -0.29161935 -0.93733471 ... -0.0766641  -0.23639369
 -0.44582637]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.72577295  1.48836963 -1.67427109 ... -1.28398119 -0.15034217
 -0.57392894]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.42149902 -0.16445544 -0.55002081 ... -0.6785426   0.73519711
 -0.6785426 ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.16455711  0.48834154 -1.14390508 ... -0.16455711  0.32511688
 -0.49100643]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.06327437  0.76473737 -1.16729002 ... -0.61528219  0.48873346
 -0.33927828]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[-0.67891464 -0.36858985 -0.67891464 ... -0.67891464 -0.67891464
 -0.36858985]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()
/tmp/ipykernel_2494/31820027.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[ 0.24575036  0.8062671  -1.15554147 ... -0.31476637  1.08652546
 -0.59502474]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df_ohe.loc[:,cont_columns] = (df_ohe.loc[:,cont_columns] - df_ohe.loc[:,cont_columns].mean()) / df_ohe.loc[:,cont_columns].std()

In [ ]:
df_ohe.loc[:,cont_columns].mean()

Age                       -1.389667e-17
DailyRate                  5.075305e-17
DistanceFromHome           6.525392e-17
HourlyRate                 1.836777e-16
MonthlyIncome             -3.866899e-17
MonthlyRate                2.779334e-17
TotalWorkingYears         -3.141856e-17
YearsAtCompany            -2.658493e-17
YearsInCurrentRole         1.075481e-16
YearsSinceLastPromotion   -1.329247e-17
YearsWithCurrManager      -1.691768e-17
dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
df_ohe.loc[:,cont_columns] = sc.fit_transform(df_ohe.loc[:,cont_columns])
df_ohe.loc[:,cont_columns].mean()

Age                       -1.450087e-17
DailyRate                  3.625218e-17
DistanceFromHome           2.416812e-18
HourlyRate                -3.866899e-17
MonthlyIncome             -3.987740e-17
MonthlyRate                1.208406e-17
TotalWorkingYears          1.208406e-17
YearsAtCompany            -2.779334e-17
YearsInCurrentRole         3.383537e-17
YearsSinceLastPromotion    1.812609e-17
YearsWithCurrManager       2.416812e-17
dtype: float64

In [ ]:
df.columns[df.isna().sum()/len(df) *100 > 90]

Index([], dtype='object')