# Customer segmentation on E commerce data

https://www.kaggle.com/datasets/carrie1/ecommerce-data

In [2]:
import pandas as pd
df = pd.read_csv("/content/customer_data.csv",
                 encoding="iso-8859-1")
df.shape

(541909, 8)

In [3]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [4]:
df.drop(columns=['Description'],inplace=True)

In [5]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
df.dropna(inplace=True)

In [7]:
df.shape

(406829, 7)

In [8]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CustomerID', 'Country'],
      dtype='object')

In [9]:
df['Price'] = df['Quantity']*df['UnitPrice']

In [10]:
df.columns

Index(['InvoiceNo', 'StockCode', 'Quantity', 'InvoiceDate', 'UnitPrice',
       'CustomerID', 'Country', 'Price'],
      dtype='object')

In [11]:
df_1 = df.groupby(['InvoiceNo','InvoiceDate','CustomerID'])['Price'].sum().reset_index()

In [12]:
df_1.head()

  InvoiceNo     InvoiceDate  CustomerID   Price
0    536365  12/1/2010 8:26     17850.0  139.12
1    536366  12/1/2010 8:28     17850.0   22.20
2    536367  12/1/2010 8:34     13047.0  278.73
3    536368  12/1/2010 8:34     13047.0   70.05
4    536369  12/1/2010 8:35     13047.0   17.85

In [14]:
df_1.shape

(22221, 4)

In [16]:
df_1 = df_1.loc[df_1['Price'] > 0,:]

In [17]:
df_1.shape

(18562, 4)

In [ ]:
# customer id , total no of invoices, total spent,
# std dev of spent in invoice
# days from last invoice

In [20]:
df_2 = df_1.groupby(['CustomerID']).agg({'Price':'sum',
                                  'InvoiceNo':'count',
                                  'InvoiceDate':'max'}).reset_index()

In [21]:
df_2.head()

   CustomerID     Price  InvoiceNo      InvoiceDate
0     12346.0  77183.60          1  1/18/2011 10:01
1     12347.0   4310.00          7    8/2/2011 8:48
2     12348.0   1797.24          4  9/25/2011 13:13
3     12349.0   1757.55          1  11/21/2011 9:51
4     12350.0    334.40          1   2/2/2011 16:01